#' Forecast values using chosen model
#'
#' @param selectedModel model name as a string as generated by the function modelDeveloper. String can be stored in a vector and used as well
#' @param allModelEvaluated the results as generated by modelEvaluator function
#' @return Returns a dataframe with predicted values
#' @export
#' @examples
#' selectedModelForecaster(selectedModel,allModelEvaluated)

selectedModelForecaster <- function(selectedModel,allModelEvaluated){
  predicted_values <- predict(selectedModelObject,newdata = forecast_df)
  used_vars <- trimws(unlist(strsplit(selectedModel,"[+,~]")))
  keep_vars<- c("Date",used_vars,"predicted_values")
  predicted_df <- data.table(cbind(forecast_df,predicted_values))[,..keep_vars]
  return(predicted_df)
}

#' Chart the model selected
#'
#' @param selectedModel model name as a string as generated by the function modelDeveloper. String can be stored in a vector and used as well
#' @param allModelEvaluated the results as generated by modelEvaluator function
#' @return Returns ggplot
#' @export
#' @examples
#' selectedModelForecaster(selectedModel,allModelEvaluated)

selectedModelCharter <- function(selectedModel,allModelEvaluated){

predicted_df<- selectedModelForecaster(selectedModel,allModelEvaluated)
ODR <- trimws(unlist(strsplit(selectedModel,'[~]'))[[1]])
  ggplot(predicted_df, aes(lubridate::dmy(Date))) +
    geom_line(aes(y = predicted_values, colour = "predicted"))+
    geom_line(aes(y = get(ODR), colour = "DR")) +xlab("Date")+ ylab("Default Rates")
}

  # predicted.melt<-data.table::melt(predicted_df,c("Date"),setdiff(used_vars,"DR"))
  #
  # ggplot(predicted.melt, aes(x = lubridate::dmy(Date), y = value)) + geom_line(colour =
  #                                                                                c_green) + xlab("Date")+ facet_wrap( ~ variable, scales = 'free')
