#' Show pretty table with diagnostic tests and results for the selected Model
#'
#' @param selectedModel model name as a string as generated by the function modelDeveloper. String can be stored in a vector and used as well
#' @param allModelEvaluated the results as generated by modelEvaluator function
#' @return Returns a table, using formattable
#' @export
#' @examples
#' selectedModelDiagnostics("DR ~ ECI_yoy_ch_3QMA_lag_4+avg_oil_pri_barrel_3QMA_lag_1",allModelEvaluated) # allModelEvaluated created by modelEvaluator()
#' selectedModel <- "DR ~ ECI_yoy_ch_3QMA_lag_4+avg_oil_pri_barrel_3QMA_lag_1"
#' selectedModelDiagnostics(selectedModel,allModelEvaluated) # allModelEvaluated created by modelEvaluator()

selectedModelDiagnostics <- function(selectedModel,allModelEvaluated){

  c_red1 <- "#f15b27"
  c_red2 <- "#eb4955"
  c_green1 <- "#bad532"
  c_green2 <- "#84c444"
  c_green3 <- "#00a054"
  c_green <- "#01b5aa"

  chosenModelResults <-allModelEvaluated[model==selectedModel,]

  # select all stats and pvalues that is to be displayed.
  stats <- do.call(paste0,CJ(c("BP","dw","shapiro","adf"),c("_pvalue","_statistic","_results")))
  chosenModelResults.stats <- chosenModelResults[, .SD, .SDcols = stats][, rn := .I]

  chosenModelResults.melt <-melt(chosenModelResults.stats,'rn')[, c('stub', 'var') := tstrsplit(variable, "_")][,dcast(.SD, stub ~ var)]

  #Creiteris for Display
  Criteria <- data.table(Check=c("Heteroskedasticity", "Auto-Correlation", "Normality", "Unit Root", "Multicollinearity"),
                         Test=c("Breusch-Pagan Test", "Durbin Watson Test", "Shapiro-Wilk Test", "ADF Test", "VIF"),
                         stub=c( "BP", "dw", "shapiro", "adf", NA),
                         Criteria=c( "p > 0.1", "p > 0.1", "p > 0.1", "p < 0.1", "<4"), # this is just for information, the values arent being used anywhere. NO threshold check is being done using this table
                         Pass=c("Homoskedasticity", "No Auto-Correlation", "Residuals Normally distributed", "Stationary", "No Multicollinearity")
  )

  chosenModelResults_informative <- Criteria[chosenModelResults.melt,on="stub"]
  chosenModelResults_informative[, FINAL:=ifelse(Pass == results, "PASS", "FAIL")]
  chosenModelResults_pretty<-chosenModelResults_informative[,c('Check','Test','statistic','pvalue','Criteria','results','FINAL')]

  #return(chosenModelResults_pretty)

  #apply formatting through formattable

  formattable(chosenModelResults_pretty, list(
    FINAL = formattable:: formatter("span",
                                    style = x ~ formattable::style(color = ifelse(
                                      x == "FAIL", c_red1, c_green
                                    )),
                                    x ~ icontext(ifelse(
                                      x == "FAIL", "remove", "ok"
                                    )))
  ))

}

