#' Show pretty table with results of the regression for the selected Model
#'
#' @param selectedModel model name as a string as generated by the function modelDeveloper. String can be stored in a vector and used as well
#' @param allModelEvaluated the results as generated by modelEvaluator function
#' @return Returns a table, using formattable
#' @export
#' @examples
#' selectedModelDiagnostics("DR ~ ECI_yoy_ch_3QMA_lag_4+avg_oil_pri_barrel_3QMA_lag_1",allModelEvaluated) # allModelEvaluated created by modelEvaluator()
#' selectedModel <- "DR ~ ECI_yoy_ch_3QMA_lag_4+avg_oil_pri_barrel_3QMA_lag_1"
#' selectedModelDiagnostics(selectedModel,allModelEvaluated) # allModelEvaluated created by modelEvaluator()

selectedModelRegressionResults <- function(selectedModel,allModelEvaluated,direction_config=macrometa,pvalue_threshold =0.05){

  # c_red1 <- "#f15b27"
  # c_red2 <- "#eb4955"
  # c_green1 <- "#bad532"
  # c_green2 <- "#84c444"
  # c_green3 <- "#00a054"
  # c_green <- "#01b5aa"

  selectedModel <-allModelEvaluated$model
  chosenModelResults <- allModelEvaluated[model==selectedModel,]

  model_LHS <- trimws(unlist(strsplit(selectedModel, "[~]"))[[1]])
  RHS_combined <- trimws(unlist(strsplit(selectedModel, "[~]"))[[2]])
  used_vars <- trimws(unlist(strsplit(RHS_combined, '[+]')))

  used_vars_intercept <- c(used_vars,"(Intercept)")
  setnames(chosenModelResults,used_vars_intercept,paste0("Estimates.",used_vars_intercept))
  # select all stats and pvalues that is to be displayed.
  stats <- do.call(paste0,CJ( c("se.","t.","p."),used_vars_intercept))
  vif_stats<- paste0("VIF.",used_vars)
  keep_cols<- c(stats,vif_stats,paste0("Estimates.",used_vars_intercept))
  chosenModelResults.stats <- chosenModelResults[, .SD, .SDcols = keep_cols][, rn := .I]

  chosenModelResults.melt <- melt(chosenModelResults.stats,
                                  "rn")
  # replace dot with  colon since sometimes the variables will have dots in it, which will cause trstrplit operation below to fail
  chosenModelResults.melt$variable <- sub("[.]",":",chosenModelResults.melt$variable)

  chosenModelResults.melt<- chosenModelResults.melt[, `:=`(c("stub", "var"), tstrsplit(variable, "[:]"))][,dcast(.SD, var ~ stub)]
  # chosenModelResults.melt <-  melt(chosenModelResults.stats,'rn')[, c('stub', 'var') := tstrsplit(variable, "[.]")][,dcast(.SD,  var ~ stub)]
  #Creiteris for Display


  lookup <- direction_config$Type
  names(lookup) <- direction_config$Variable
  chosenModelResults.melt$sign <- sign(chosenModelResults.melt$Estimates)
  chosenModelResults.melt$lookedup <- lookup[chosenModelResults.melt$var]
  chosenModelResults.melt[var != "(Intercept)",DirectionCheck:=ifelse(sign==lookedup,"PASS","FAIL")]

  chosenModelResults.melt[,Significance := ifelse(p < pvalue_threshold,"PASS","FAIL")]
  chosenModelResults.melt[,Multicollinearity := ifelse(VIF < 4,"PASS","FAIL")]

  chosenModelResults.melt[,sign:=NULL][,lookedup:=NULL]

  otherStats <- c("R2","adjR2","MAPE_test")
  otherStats_df <- chosenModelResults[,otherStats,with=FALSE]
  otherStats_kable <- t(otherStats_df)%>% kable(escape = F) %>%
    kable_styling(bootstrap_options = "striped", full_width = F, font_size = 10)

  estimates_kable <-chosenModelResults.melt %>%
    mutate(
      DirectionCheck = ifelse(DirectionCheck=="PASS",
                              cell_spec(DirectionCheck, "html", color = "green", bold = T),cell_spec(DirectionCheck, "html", color = "red", bold = T)
                              )) %>%
    mutate(
      Significance = ifelse(Significance=="PASS",
              cell_spec(Significance, "html", color = "green", bold = T),
              cell_spec(Significance, "html", color = "red", bold = T)
      )) %>%
    mutate(
      Multicollinearity = ifelse(Multicollinearity=="PASS",
              cell_spec(Multicollinearity, "html", color = "green", bold = T),
              cell_spec(Multicollinearity, "html", color = "red", bold = T)
      )) %>%
    mutate(
      p = ifelse(p < pvalue_threshold,
        cell_spec(p, "html", color = "white",background = "green",bold = T),
        cell_spec(p, "html", color = "white",background = "red", bold = T)
                 )
    ) %>%
    kable(escape = F) %>%
    kable_styling(bootstrap_options = "striped", full_width = F, font_size = 10)

  list(estimates_kable=estimates_kable,otherStats_kable=otherStats_kable)


}
